apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-integration.fullname" . }}
  labels:
    app: {{ template "radar-integration.name" . }}
    chart: {{ template "radar-integration.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  radar.yml: |
    version: 0.1-alpha
    released: 2017-08-29

    # ManagementPortal configuration
    management_portal:
      oauth_client_id: {{ .Values.oauth_client_id }} #OAuth2 clientId used by the webApp for making requests
      oauth_client_secret: {{ .Values.oauth_client_secret }} #OAuth2 client secret
      base_url: http://{{ .Values.management_portal_url }}:8080/managementportal/ #Base URL of the Management Portal

    # Set of supported projects
    projects:
      {{- range .Values.projects }}
      - redcap_info:
          url: {{ .url }} #URL pointing REDCap instance
          project_id: {{ .project_id }} #REDCap project identifier
          api_path: {{ .api_path }} # Redcap relative api path
          enrolment_event: {{ .enrolment_event }} #Unique identifier for the enrolment event
          integration_form: {{ .integration_form }} #Name of integration REDCap form
          token: {{ .token }} #REDCap API Token used to identify the REDCap user against the REDCap instance
        mp_info:
          # Management Portal project identifier
          project_name: {{ .mp_info_project_name }} #
      {{ end -}}
